---

- ansible.builtin.import_tasks: version-check.yml
  tags: updates-only

- ansible.builtin.import_tasks: user.yml

- ansible.builtin.import_tasks: install.yml
  tags: updates-only

- ansible.builtin.import_tasks: config.yml

- ansible.builtin.import_tasks: systemd.yml
