---

- name: delete admin credentials envfile
  ansible.builtin.file:
    path: "{{ keycloak.admin.envfile }}"
    state: absent

- name: Update desktop entry database
  ansible.builtin.command: >
    /usr/bin/update-desktop-database -v {{ xdg_desktop_entries }}
